site_name: HaoBIT 博客
site_description: 关于 HaoBIT 等。
site_url: https://blog.haobit.top/
repo_url: https://github.com/Capchdo/blog
repo_name: Capchdo/blog
edit_uri: "blob/main/docs/"

locale: zh-CN
# `locale` will be a warning, but used in RSS.
# https://github.com/mkdocs/mkdocs/pull/2299

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      primary: green
      toggle:
        icon: material/brightness-auto
        name: 切换到亮色
    - media: "(prefers-color-scheme: light)"
      primary: green
      scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换到暗色
    - media: "(prefers-color-scheme: dark)"
      primary: green
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 自动设置亮暗
  language: zh
  custom_dir: overrides
  features:
    - content.code.copy
    - content.action.view
    - content.action.edit
    - navigation.top
    - search.highlight
  logo: assets/logo.png
  favicon: assets/favicon-32x32.png

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds: {}
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - mdx_truly_sane_lists

plugins:
  # If no plugins entry is set, MkDocs enables search by default, otherwise I have to declare it explicitly.
  - search:
      separator: '[\s\u200b\-]'
      # 零宽空格用于中文搜索

  # Extra plugins
  # Some plugins are disabled for faster build times in development.
  - rss:
      enabled: !ENV [CI, false]
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
      type: iso_date
      timezone: Asia/Shanghai
  - privacy:
      enabled: !ENV [CI, false]

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: simple/rss
      link: https://blog.haobit.top/feed_rss_updated.xml
      name: RSS
  analytics:
    provider: custom
    property: 1ea80865c430437decf2e0e6bc4ae4c8
  comments: true
