name: deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - '.pre-commit-config.yaml'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # RSS plugin needs all history
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Set cache ID
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Setup just
        uses: taiki-e/install-action@v2
        with:
            tool: just
      - run: just bootstrap
      - run: mkdocs gh-deploy --force --no-history

