name: links

on:
  repository_dispatch:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: >-
            --config .github/config/lychee.toml
            .
      - name: Find last link-checker issue
        id: link-checker-issue
        uses: micalevisk/last-issue-action@v1
        with:
          state: open
          labels: |
            link-checker
      - name: Create or update issue
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          # Update an existing issue if one was found (issue-number),
          # otherwise an empty value creates a new issue:
          issue-number: "${{ steps.link-checker-issue.outputs.issue_number }}"
          content-filepath: ./lychee/out.md
          labels: automated issue, link-checker
